[profile.default]
src = "foundry/src"
out = "foundry/out"
broadcast = "foundry/broadcast"
libs = ["foundry/lib"]
test = "foundry/test"
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "forge-std/=foundry/lib/forge-std/src/"
]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Test configuration
[profile.test]
verbosity = 2
gas_reports = ["*"]
match_path = "test/*"